apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-test
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: master
  url: https://github.com/muhammadnkhan/flux-test.git
